services:
  app:
    build:
      context: .
    ports:
      - 3000:3000
    volumes:
      - ..:/workspace:cached
      - node_modules:/workspace/node_modules
    command: sleep infinity

  db:
    image: mongodb/mongodb-community-server:7.0.3-ubi9
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  node_modules:
  mongo-data:
